name = "tgb-calendar-web"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[[d1_databases]]
binding = "DB"
database_name = "tgb-calendar"
database_id = "6f50f43e-7174-42a1-b5ed-b19e26a08cef"
migrations_dir = "../../db/migrations"
