name = "tgb-calendar-web"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[observability]
enabled = true

[[d1_databases]]
binding = "DB"
database_name = "tgb-cal"
database_id = "c70655ae-45cc-4052-9213-e567a4ab53d0"
migrations_dir = "../../db/migrations"
